In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option('display.max_columns', None)

# Load dataset
df = pd.read_csv("credit_risk_dataset.csv")  # change file name

# Preview
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_int_rate_decimal,interest_earned,actual_profit
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0.1602,5607.00,-35000.0
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0.1114,111.40,111.4
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0.1287,707.85,-5500.0
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0.1523,5330.50,-35000.0
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0.1427,4994.50,-35000.0

In [2]:
# Shape of dataset
print("Shape:", df.shape)

# Column names
print("\nColumns:\n", df.columns)

# Data types
print("\nData Types:\n")
print(df.dtypes)

# Info summary
print("\nInfo:\n")
df.info()

Shape: (31529, 15)

Columns:
 Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length',
       'loan_int_rate_decimal', 'interest_earned', 'actual_profit'],
      dtype='object')

Data Types:

person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
loan_int_rate_decimal         float64
interest_earned               float64
actual_profit                 float64
dtype: object

Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31529 entries, 0 to 31528
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  31529 non-null  int64
 1   person_income               31529 non-null  int64
 2   person_home_ownership       31529 non-null  object
 3   person_emp_length           31529 non-null  float64
 4   loan_intent                 31529 non-null  object
 5   loan_grade                  31529 non-null  object
 6   loan_amnt                   31529 non-null  int64
 7   loan_int_rate               31529 non-null  float64
 8   loan_status                 31529 non-null  int64
 9   loan_percent_income         31529 non-null  float64
 10  cb_person_default_on_file   31529 non-null  object
 11  cb_person_cred_hist_length  31529 non-null  int64
 12  loan_int_rate_decimal       31529 non-null  float64
 13  interest_earned             31529 non-null  float64
 14  actual_profit               31529 non-null  float64
dtypes: float64(6), int64(5), object(4)
memory usage: 3.6+ MB

In [3]:
# Count missing values
missing_values = df.isnull().sum()

# Percentage missing
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing %': missing_percent
})

print(missing_df[missing_df['Missing Count'] > 0])

Empty DataFrame
Columns: [Missing Count, Missing %]
Index: []

In [4]:
# Total duplicate rows
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

# Optional: View duplicate rows
df[df.duplicated()]

Duplicate rows: 0

Empty DataFrame
Columns: [person_age, person_income, person_home_ownership, person_emp_length, loan_intent, loan_grade, loan_amnt, loan_int_rate, loan_status, loan_percent_income, cb_person_default_on_file, cb_person_cred_hist_length, loan_int_rate_decimal, interest_earned, actual_profit]
Index: []

In [5]:
df = df.drop_duplicates()

In [6]:
# Outlier Detection

num_cols = df.select_dtypes(include=np.number).columns
print("Numeric Columns:\n", num_cols)

Numeric Columns:
 Index(['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_cred_hist_length', 'loan_int_rate_decimal',
       'interest_earned', 'actual_profit'],
      dtype='object')

In [7]:
# Drop rows where person_emp_length is missing (<5%)
df = df.dropna(subset=['person_emp_length'])

# Fill loan_int_rate with median (>5%)
df['loan_int_rate'] = df['loan_int_rate'].fillna(df['loan_int_rate'].median())

In [8]:
df[num_cols].describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length,loan_int_rate_decimal,interest_earned,actual_profit
count,31529.000000,3.152900e+04,31529.00000,31529.000000,31529.000000,31529.000000,31529.000000,31529.000000,31529.000000,31529.000000,31529.000000
mean,27.759238,6.670447e+04,4.79051,9665.152717,11.040066,0.215928,0.169660,5.816201,0.110401,1094.028544,-1599.074177
std,6.366137,6.245756e+04,4.14549,6336.661842,3.071733,0.411471,0.106324,4.064782,0.030717,866.417748,6001.101053
min,20.000000,4.000000e+03,0.00000,500.000000,5.420000,0.000000,0.000000,2.000000,0.054200,48.800000,-35000.000000
25%,23.000000,3.945600e+04,2.00000,5000.000000,8.490000,0.000000,0.090000,3.000000,0.084900,489.300000,186.780000
50%,26.000000,5.600000e+04,4.00000,8000.000000,10.990000,0.000000,0.150000,4.000000,0.109900,839.400000,594.600000
75%,30.000000,8.000000e+04,7.00000,12500.000000,13.160000,0.000000,0.230000,8.000000,0.131600,1428.700000,1110.600000
max,144.000000,6.000000e+06,123.00000,35000.000000,23.220000,1.000000,0.830000,30.000000,0.232200,7087.500000,6891.500000

In [9]:
df['loan_status'].value_counts(normalize=True)

loan_status
0    0.784072
1    0.215928
Name: proportion, dtype: float64

**Adding Columns**

In [10]:
# If interest rate is in percentage (e.g., 13.5), convert to decimal
df['loan_int_rate_decimal'] = df['loan_int_rate'] / 100

# Interest earned per loan
df['interest_earned'] = df['loan_amnt'] * df['loan_int_rate_decimal']

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_int_rate_decimal,interest_earned,actual_profit
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0.1602,5607.00,-35000.0
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0.1114,111.40,111.4
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0.1287,707.85,-5500.0
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0.1523,5330.50,-35000.0
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0.1427,4994.50,-35000.0

In [11]:
#Actual Profit Column

df['actual_profit'] = np.where(
    df['loan_status'] == 0,
    df['interest_earned'],
    -df['loan_amnt']
)

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_int_rate_decimal,interest_earned,actual_profit
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0.1602,5607.00,-35000.0
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0.1114,111.40,111.4
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0.1287,707.85,-5500.0
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0.1523,5330.50,-35000.0
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0.1427,4994.50,-35000.0

In [12]:
# Revenue amount

total_revenue = df.loc[df['loan_status'] == 0, 'interest_earned'].sum()
print("Total Revenue:", total_revenue)

Total Revenue: 24650640.275

In [13]:
# Total Loss amount

total_loss = df.loc[df['loan_status'] == 1, 'loan_amnt'].sum()
print("Total Loss:", total_loss)

Total Loss: 75067850

In [14]:
# Net profit amount

net_profit = total_revenue - total_loss
print("Net Profit:", net_profit)

Net Profit: -50417209.725

In [15]:
# Profit per Loan amount

profit_per_loan = df['actual_profit'].mean()
print("Profit Per Loan:", profit_per_loan)

Profit Per Loan: -1599.0741769482065

In [16]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_int_rate_decimal,interest_earned,actual_profit
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0.1602,5607.00,-35000.0
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0.1114,111.40,111.4
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0.1287,707.85,-5500.0
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0.1523,5330.50,-35000.0
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0.1427,4994.50,-35000.0

In [17]:
df.to_csv("credit_risk_dataset.csv", index=False)

In [18]:
import os
os.listdir()

['.ipynb_checkpoints',
 '.virtual_documents',
 'anaconda_projects',
 'BNPL_Credit_Risk_Project.ipynb',
 'credit_risk_dataset.csv',
 'Segment Analysis']

In [19]:
len(df.columns)

15

In [20]:
df.columns

Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length',
       'loan_int_rate_decimal', 'interest_earned', 'actual_profit'],
      dtype='object')

In [21]:
df.dtypes

person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
loan_int_rate_decimal         float64
interest_earned               float64
actual_profit                 float64
dtype: object

In [22]:
total_loans = len(df)
print("Total Loans:", total_loans)

Total Loans: 31529

In [23]:
default_rate = df['loan_status'].mean()

print("Default Rate:", default_rate)
print("Default Rate (%):", default_rate * 100)

Default Rate: 0.21592819309207395
Default Rate (%): 21.592819309207396

In [26]:
#Risk Model


import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score

# Load dataset
df = pd.read_csv("credit_risk_dataset.csv")

# Target
y = df["loan_status"]

# Features
X = df[[
    "loan_percent_income",
    "person_income",
    "person_age",
    "loan_amnt",
    "loan_int_rate_decimal",
    "person_emp_length",
    "cb_person_cred_hist_length",
    "cb_person_default_on_file",
    "loan_grade",
    "person_home_ownership",
    "loan_intent"
]]

# Categorical columns
categorical_cols = [
    "cb_person_default_on_file",
    "loan_grade",
    "person_home_ownership",
    "loan_intent"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first"), categorical_cols)
    ],
    remainder="passthrough"
)

# Model pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# Separate numeric and categorical columns
numeric_cols = [
    "loan_percent_income",
    "person_income",
    "person_age",
    "loan_amnt",
    "loan_int_rate_decimal",
    "person_emp_length",
    "cb_person_cred_hist_length"
]

categorical_cols = [
    "cb_person_default_on_file",
    "loan_grade",
    "person_home_ownership",
    "loan_intent"
]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(drop="first"), categorical_cols)
    ]
)

model = Pipeline([
    ("preprocess", preprocessor),
    ("classifier", LogisticRegression(max_iter=2000))
])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model.fit(X_train, y_train)

# Predict probabilities
df["predicted_risk"] = model.predict_proba(X)[:, 1]

# Check AUC
auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print("Model AUC:", auc)

Model AUC: 0.8672167040960502

In [28]:
# Simulate Rejecting Top 20% Risky Loans

# BEFORE metrics
total_loans_before = len(df)
total_profit_before = df["actual_profit"].sum()
profit_per_loan_before = df["actual_profit"].mean()

print("BEFORE")
print("Total Loans:", total_loans_before)
print("Total Profit:", total_profit_before)
print("Profit per Loan:", profit_per_loan_before)


# Remove top 20% highest risk loans
risk_threshold = df["predicted_risk"].quantile(0.80)

df_filtered = df[df["predicted_risk"] <= risk_threshold]

# AFTER metrics
total_loans_after = len(df_filtered)
total_profit_after = df_filtered["actual_profit"].sum()
profit_per_loan_after = df_filtered["actual_profit"].mean()

print("\nAFTER Removing Top 20% Risky Loans")
print("Total Loans:", total_loans_after)
print("Total Profit:", total_profit_after)
print("Profit per Loan:", profit_per_loan_after)

BEFORE
Total Loans: 31529
Total Profit: -50417209.725
Profit per Loan: -1599.0741769482065

AFTER Removing Top 20% Risky Loans
Total Loans: 25223
Total Profit: -1437525.6799999992
Profit per Loan: -56.99265273758075

In [29]:
print("Default Rate BEFORE:", df["loan_status"].mean())
print("Default Rate AFTER:", df_filtered["loan_status"].mean())

Default Rate BEFORE: 0.21592819309207395
Default Rate AFTER: 0.09463584823375491